name: Run Notebook
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: Lint with ruff (ignore .gitignore files)
        shell: micromamba-shell {0}
        run: |
          # Generate a comma-separated list of ignored folders/files
          EXCLUDE=$(git ls-files --others --directory --ignored --exclude-standard | paste -sd "," -)
          
          echo "Excluding the following files/folders from linting: $EXCLUDE"
          
          # Run ruff linting, excluding ignored files/folders
          ruff check . --exclude "$EXCLUDE"
          ruff format --check . --exclude "$EXCLUDE"

      - name: Run notebook
        shell: micromamba-shell {0}
        run: |
          PYTHONPATH=src pytest --nbmake notebook.ipynb
